name: Build and Release a Next.js app
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
    build-project:
        name: build next.js project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install npm dependencies
              run: make install
            - name: Build Next.js project
              run: make run
            - name: Upload build artifacts to registry
              uses: actions/upload-artifact@v4
              with:
                name: code-drop
                path: .next/
    download-artifacts-and-release:
      permissions:
        contents: write  
      needs: build-project
      name: Download Next.js artifacts and release
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts from registry
          uses: actions/download-artifact@v4
          with:
            name: code-drop
        - name: Compressing downloaded artifacts
          run: |
            zip -r artifacts.zip .
        - name: List out download files (verification)
          run: ls -ltr
        - name: Create Release (zipped code files)
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          with:
            tag_name: v${{ github.run_number }}.0.0
            release_name: Release v${{ github.run_number }}.0.0
