name: Webhook triggered (self-hosted runner)

on:
  repository_dispatch:
    types: # These are `event_type` in your POST request
      - webhook
      - curl-trigger

jobs:
  respond-to-webhook:
    runs-on: self-hosted
    steps:
      - name: "Webhook payload message"
        run: |
          - echo "Job ran using github self-hosted runner"
          - ${{ github.event.client_payload.message }}