name: Webhook triggered workflow

on:
  repository_dispatch:
    types: [webhook]

jobs:
  read-webhook-payload:
    name: "Read Webhook payload"
    runs-on: ubuntu-latest
    steps:
      - name: "Print webhook message"
        env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo "$MESSAGE"
  process-webhook-data:
    name: "Process Webhook data"
    needs: read-webhook-payload
    runs-on: ubuntu-latest
    steps:
      - name: "Stage 2"
        run: echo "placeholder"
  send-slack-notification:
    name: "Send Slack Notification"
    runs-on: ubuntu-latest
    steps:
      - name: "Slack notification"
        run: echo "placeholder"